title: Tandem Young
description: "PhD student in economics at the University of Arkansas. Research in applied microeconomics, regional economic development, and health economics."
author: Tandem Young
url: "https://tandemyoung.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - .DS_Store
